# Merge of all Dimensions (real-estate, commercial, social) into one dataframe ready for modeling

In [1]:
import pandas as pd

In [31]:
#load dataframes re, c, s 
re_df = pd.read_csv("/Users/mareikesahling/Ginger_Gradient/Capstone/capstone-kiezkeeper/data/final_datasets/re_variables.csv",dtype={"plr_id": str})
c_df = pd.read_csv("/Users/mareikesahling/Ginger_Gradient/Capstone/capstone-kiezkeeper/data/final_datasets/feature_matrix_commercial_reduced.csv",dtype={"plr_id": str})
s_df = pd.read_csv("/Users/mareikesahling/Ginger_Gradient/Capstone/capstone-kiezkeeper/data/final_datasets/social_features.csv",dtype={"plr_id": str})

In [32]:
re_df.head()

,plr_id,plr_name,bez,re_miete_niveau,re_miete_niveau_vs_bez,re_miete_niveau_vs_berlin,re_miete_trend,re_miete_trend_vs_bez,re_miete_trend_vs_berlin,re_miete_unsicher,...,re_dichte_all,re_baualter_unsicher,re_anteil_vor_1919,re_anteil_y1919_1948,re_anteil_y1949_1978,re_anteil_y1979_1990,re_anteil_y1991_2000,re_anteil_y2001_2010,re_anteil_y2011_plus,re_miet_dimension_anwendbar
0,01100101,Stülerstraße,01 - Mitte,22.70,1.020478,1.650489,2.142,1.224713,1.380585,0,...,10.653753,0.0,0.118160,0.008232,0.561743,0.148668,0.062954,0.000000,0.102663,1
1,01100102,Großer Tiergarten,01 - Mitte,20.30,0.483545,1.123496,1.059,-0.391013,-0.102295,0,...,24.075666,0.0,0.228719,0.015477,0.020636,0.083405,0.354256,0.226999,0.070507,1
2,01100103,Lützowstraße,01 - Mitte,23.00,1.087595,1.716363,1.356,0.052081,0.304367,0,...,16.223680,0.0,0.323783,0.050742,0.255782,0.188126,0.049707,0.037280,0.092855,1
3,01100104,Körnerstraße,01 - Mitte,26.21,1.805742,2.421217,2.276,1.424627,1.564063,0,...,24.819856,0.0,0.277822,0.030825,0.324259,0.172938,0.004404,0.075260,0.114492,1
4,01100205,Wilhelmstraße,01 - Mitte,26.08,1.776659,2.392672,1.583,0.390742,0.615183,0,...,24.963289,0.0,0.168869,0.004405,0.041850,0.306167,0.225404,0.174743,0.079295,1

In [33]:
c_df.head()

,plr_id,com_median_age_level_2026,com_share_solo_level_2026,com_share_10plus_level_2026,com_gastro_share_level_2026,com_upscale_share_level_2026,com_tourism_share_level_2026,com_median_age_slope,com_share_max_2y_slope,com_share_min_20y_slope,com_share_min_30y_slope,com_share_min_40y_slope,com_share_solo_slope,com_share_10plus_slope,com_gastro_share_slope,com_upscale_share_slope,com_tourism_share_slope,com_n_gastro,com_has_gastro_structure
0,01100101,8.0,0.489786,0.101146,0.017607,0.692308,0.017156,-0.301931,-0.001224,0.005658,0.001367,-0.000276,0.024083,0.002754,0.003153,-0.036026,-0.001193,13.000000,1
1,01100102,7.0,0.449551,0.126353,0.083164,0.621134,0.007180,0.277992,-0.013687,0.004813,0.003015,0.001063,0.028592,0.002506,0.004856,-0.035559,-0.000066,129.333333,1
2,01100103,7.0,0.499170,0.081557,0.031358,0.585551,0.011446,0.196911,0.021270,0.008188,0.001498,0.001101,0.032530,-0.001222,0.000177,-0.010159,-0.001967,43.833333,1
3,01100104,7.0,0.562960,0.098171,0.037814,0.643979,0.004752,-0.083398,0.009634,0.006168,0.000819,0.001799,0.028447,0.000038,0.001706,-0.041468,0.000023,31.833333,1
4,01100205,6.0,0.460174,0.111225,0.063733,0.628225,0.013926,0.479537,-0.061504,0.006034,0.001334,0.000460,0.015370,0.003292,0.002437,-0.019498,0.000424,109.833333,1

In [34]:
#add the social prefix for the social dimension 
s_df = s_df.rename(
    columns=lambda col: col if col in ["plr_id", "plr_name"] else "soc_" + col
)
s_df.head()

,plr_id,plr_name,soc_median_income_2023,soc_young_to_middle_adult_share_2025,soc_young_to_middle_adult_share_change_2021_2025,soc_single_person_hh_share_2024,soc_single_person_hh_share_change_2021_2024,soc_households_without_minor_children_share_2024,soc_households_without_minor_children_share_change_2021_2024,soc_internal_migration_volume_rate_2025,soc_internal_migration_volume_rate_change_2021_2025,soc_internal_net_migration_rate_2025,soc_internal_net_migration_rate_change_2021_2025,soc_transfer_benefit_share_2024,soc_transfer_benefit_share_change_2020_2024,soc_single_parent_household_share_2024,soc_single_parent_household_share_change_2021_2024
0,01100101,Stülerstraße,4721.0,0.460,0.000,0.624,-0.004,0.888,-0.019,0.236,0.025,-0.056,-0.043,0.080,-0.000,0.027,0.005
1,01100102,Großer Tiergarten,6279.0,0.479,0.003,0.535,-0.010,0.870,0.005,0.199,0.017,0.008,0.006,0.027,-0.008,0.025,-0.011
2,01100103,Lützowstraße,4895.0,0.455,0.022,0.603,0.006,0.866,-0.003,0.172,0.005,0.005,-0.002,0.118,-0.037,0.035,-0.001
3,01100104,Körnerstraße,5062.0,0.507,-0.020,0.584,0.006,0.845,0.005,0.215,0.034,0.003,0.017,0.144,-0.036,0.034,-0.004
4,01100205,Wilhelmstraße,5384.0,0.493,-0.003,0.548,0.043,0.885,0.013,0.243,-0.038,-0.035,-0.049,0.047,-0.016,0.023,-0.005

In [40]:
#re_df and s_df both have plr_id and plr_name
check = (
    re_df[["plr_id", "plr_name"]]
    .drop_duplicates()
    .merge(
        s_df[["plr_id", "plr_name"]].drop_duplicates(),
        on="plr_id",
        suffixes=("_df_re", "_df_s")
    )
)

mismatches = check[
    check["plr_name_df_re"] != check["plr_name_df_s"]
]

mismatches.sample(39)

       plr_id            plr_name_df_re              plr_name_df_s
454  10300731            Oberfeldstraße            Oberfeldstraße
444  10200421               Helle Mitte               Helle Mitte
429  10100206            Wuhletalstraße            Wuhletalstraße
136  03601452                  Velodrom                  Velodrom
397  09200717        Dörpfeldstraße Ost       Dörpfeldstraße West
481  11300617             Fennpfuhlpark             Fennpfuhlpark
99   03300515       Blankenburger Süden       Blankenburger Süden
452  10200629            Teterower Ring            Teterower Ring
141  03701657              Thälmannpark              Thälmannpark
503  11501339           Karlshorst West           Karlshorst West
145  04100101  Jungfernheide/Plötzensee  Jungfernheide/ Plötzensee
425  10100102        Rosenbecker Straße        Rosenbecker Straße
97   03300413                 Karow Ost                 Karow Ost
96   03300412             Karow Bahnhof             Karow Bahnhof
443  10200420           Gut Hellersdorf           Gut Hellersdorf
499  11401135           Dolgenseestraße           Dolgenseestraße
437  10100314           Auersbergstraße           Auersbergstraße
114  03400830          Kissingenviertel          Kissingenviertel
115  03400831              Pankower Tor              Pankower Tor
473  11100309               Mühlengrund               Mühlengrund
430  10100207        Ahrensfelder Berge        Ahrensfelder Berge
467  11100203            Falkenberg Ost            Falkenberg Ost
382  09100202          Plänterwald West          Plänterwald West
477  11200513        Große-Leege-Straße        Große-Leege-Straße
85   03100101              Bucher Forst              Bucher Forst
435  10100312               Springpfuhl               Springpfuhl
489  11300725         Nibelungenviertel         Nibelungenviertel
427  10100104           Golliner Straße           Golliner Straße
395  09200715                     Wista                     Wista
409  09401329   Kietzer Feld/Nachtheide   Kietzer Feld/ Nachtheide
199  05100102             Am Forstacker             Am Forstacker
461  10400938            Mahlsdorf Nord            Mahlsdorf Nord
128  03601244               Humannplatz               Humannplatz
469  11100205            Wartenberg Süd            Wartenberg Süd
486  11300722       Rathaus Lichtenberg       Rathaus Lichtenberg
121  03501037         Rathaus Weißensee         Rathaus Weißensee
500  11401136             Volkradstraße             Volkradstraße
504  11501340           Karlshorst Nord           Karlshorst Nord
137  03601453         Alter Schlachthof         Alter Schlachthof

In [41]:
#before merging, drop the name column 
s_df.drop(columns="plr_name", inplace=True)
s_df.head()

,plr_id,soc_median_income_2023,soc_young_to_middle_adult_share_2025,soc_young_to_middle_adult_share_change_2021_2025,soc_single_person_hh_share_2024,soc_single_person_hh_share_change_2021_2024,soc_households_without_minor_children_share_2024,soc_households_without_minor_children_share_change_2021_2024,soc_internal_migration_volume_rate_2025,soc_internal_migration_volume_rate_change_2021_2025,soc_internal_net_migration_rate_2025,soc_internal_net_migration_rate_change_2021_2025,soc_transfer_benefit_share_2024,soc_transfer_benefit_share_change_2020_2024,soc_single_parent_household_share_2024,soc_single_parent_household_share_change_2021_2024
0,01100101,4721.0,0.460,0.000,0.624,-0.004,0.888,-0.019,0.236,0.025,-0.056,-0.043,0.080,-0.000,0.027,0.005
1,01100102,6279.0,0.479,0.003,0.535,-0.010,0.870,0.005,0.199,0.017,0.008,0.006,0.027,-0.008,0.025,-0.011
2,01100103,4895.0,0.455,0.022,0.603,0.006,0.866,-0.003,0.172,0.005,0.005,-0.002,0.118,-0.037,0.035,-0.001
3,01100104,5062.0,0.507,-0.020,0.584,0.006,0.845,0.005,0.215,0.034,0.003,0.017,0.144,-0.036,0.034,-0.004
4,01100205,5384.0,0.493,-0.003,0.548,0.043,0.885,0.013,0.243,-0.038,-0.035,-0.049,0.047,-0.016,0.023,-0.005

In [42]:
df = (re_df
    .merge(s_df, on="plr_id", how="left")
    .merge(c_df, on="plr_id", how="left"))

df.head()

,plr_id,plr_name,bez,re_miete_niveau,re_miete_niveau_vs_bez,re_miete_niveau_vs_berlin,re_miete_trend,re_miete_trend_vs_bez,re_miete_trend_vs_berlin,re_miete_unsicher,...,com_share_min_20y_slope,com_share_min_30y_slope,com_share_min_40y_slope,com_share_solo_slope,com_share_10plus_slope,com_gastro_share_slope,com_upscale_share_slope,com_tourism_share_slope,com_n_gastro,com_has_gastro_structure
0,01100101,Stülerstraße,01 - Mitte,22.70,1.020478,1.650489,2.142,1.224713,1.380585,0,...,0.005658,0.001367,-0.000276,0.024083,0.002754,0.003153,-0.036026,-0.001193,13.000000,1
1,01100102,Großer Tiergarten,01 - Mitte,20.30,0.483545,1.123496,1.059,-0.391013,-0.102295,0,...,0.004813,0.003015,0.001063,0.028592,0.002506,0.004856,-0.035559,-0.000066,129.333333,1
2,01100103,Lützowstraße,01 - Mitte,23.00,1.087595,1.716363,1.356,0.052081,0.304367,0,...,0.008188,0.001498,0.001101,0.032530,-0.001222,0.000177,-0.010159,-0.001967,43.833333,1
3,01100104,Körnerstraße,01 - Mitte,26.21,1.805742,2.421217,2.276,1.424627,1.564063,0,...,0.006168,0.000819,0.001799,0.028447,0.000038,0.001706,-0.041468,0.000023,31.833333,1
4,01100205,Wilhelmstraße,01 - Mitte,26.08,1.776659,2.392672,1.583,0.390742,0.615183,0,...,0.006034,0.001334,0.000460,0.015370,0.003292,0.002437,-0.019498,0.000424,109.833333,1

In [21]:
df.sample(3)

,plr_id,plr_name,bez,re_miete_niveau,re_miete_niveau_vs_bez,re_miete_niveau_vs_berlin,re_miete_trend,re_miete_trend_vs_bez,re_miete_trend_vs_berlin,re_miete_unsicher,...,com_share_min_20y_slope,com_share_min_30y_slope,com_share_min_40y_slope,com_share_solo_slope,com_share_10plus_slope,com_gastro_share_slope,com_upscale_share_slope,com_tourism_share_slope,com_n_gastro,com_has_gastro_structure
184,4501040,Hindemithplatz,04 - Charlottenburg-Wilmersdorf,22.0,0.976167,1.496783,2.008,0.951511,1.197108,0,...,0.002416,-0.002625,-0.001273,0.021713,-0.000555,0.001051,-0.018372,-4.967747e-04,62.333333,1
136,3601452,Velodrom,03 - Pankow,24.2,1.998270,1.979860,0.762,-0.788998,-0.508958,0,...,0.002571,0.000501,0.000000,0.005319,0.000383,0.002796,-0.003604,-3.810084e-05,15.000000,1
233,5300736,Zitadellenweg,05 - Spandau,9.5,-0.695723,-1.247976,0.728,-0.308748,-0.555512,1,...,0.011545,0.000613,0.000405,0.018451,-0.000969,0.000631,-0.009212,-9.473065e-07,15.166667,1